version: '3.1'

services:

  mongo:
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo:

    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin